services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: devsnap
      POSTGRES_USER: devsnap_user
      POSTGRES_PASSWORD: devsnap_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend API
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://devsnap_user:devsnap_password@postgres:5432/devsnap
      - SECRET_KEY=dev-secret-key-change-in-production
    depends_on:
      - postgres

  # Frontend App
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
